journal:
  directory: /home/oliver/.steam/steam/steamapps/compatdata/359320/pfx/drive_c/users/steamuser/Saved
    Games/Frontier Developments/Elite Dangerous
  watch_interval: 1.0
logging:
  format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  level: INFO
server:
  cors_origins:
  - http://localhost:5173
  - https://oernster.github.io
  host: 0.0.0.0
  port: 8000
websocket:
  ping_interval: 30
  reconnect_attempts: 5
